### ISSUE TITLE
AssertionError at level end

### ISSUE THREAD

**Issue by lordmauve** [larryhastings/pyweek24#1]
```
$ python run_game.py 
Traceback (most recent call last):
  File "run_game.py", line 20, in <module>
    import main
  File "/home/mauve/dev/pyweek24/src/main.py", line 3286, in <module>
    pyglet.app.run()
  File "/home/mauve/dev/pyweek24/venv/lib/python3.6/site-packages/pyglet/app/__init__.py", line 138, in run
    event_loop.run()
  File "/home/mauve/dev/pyweek24/venv/lib/python3.6/site-packages/pyglet/app/base.py", line 142, in run
    self._run()
  File "/home/mauve/dev/pyweek24/venv/lib/python3.6/site-packages/pyglet/app/base.py", line 155, in _run
    platform_event_loop.step(timeout)
  File "/home/mauve/dev/pyweek24/venv/lib/python3.6/site-packages/pyglet/app/xlib.py", line 125, in step
    device.select()
  File "/home/mauve/dev/pyweek24/venv/lib/python3.6/site-packages/pyglet/canvas/xlib.py", line 168, in select
    dispatch(e)
  File "/home/mauve/dev/pyweek24/venv/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 922, in dispatch_platform_event_view
    event_handler(e)
  File "/home/mauve/dev/pyweek24/venv/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 1089, in _event_key_view
    self.dispatch_event('on_key_press', symbol, modifiers)
  File "/home/mauve/dev/pyweek24/venv/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1220, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "/home/mauve/dev/pyweek24/venv/lib/python3.6/site-packages/pyglet/event.py", line 357, in dispatch_event
    if handler(*args):
  File "/home/mauve/dev/pyweek24/src/main.py", line 3186, in on_key_press
    handler(True)
  File "/home/mauve/dev/pyweek24/src/main.py", line 3100, in key_escape
    game.transition_to(GameState.CONFIRM_EXIT)
  File "/home/mauve/dev/pyweek24/src/main.py", line 663, in transition_to
    player.on_game_state_change()
  File "/home/mauve/dev/pyweek24/src/main.py", line 2245, in on_game_state_change
    assert not self.pause_released_keys
AssertionError
```

**Comment by larryhastings** [comment]
Fixed, idk, quite a while ago.  Please re-open if you ever see it again, but I'm sure I fixed this.
