### ISSUE TITLE
Crash during weapon firing

### ISSUE THREAD

**Issue by lordmauve** [larryhastings/pyweek24#2]
```
$ python run_game.py                                                                                                                 
Traceback (most recent call last):
  File "run_game.py", line 20, in <module>
    import main
  File "/home/mauve/dev/pyweek24/src/main.py", line 3286, in <module>
    pyglet.app.run()
  File "/home/mauve/dev/pyweek24/venv/lib/python3.6/site-packages/pyglet/app/__init__.py", line 138, in run
    event_loop.run()
  File "/home/mauve/dev/pyweek24/venv/lib/python3.6/site-packages/pyglet/app/base.py", line 142, in run
    self._run()
  File "/home/mauve/dev/pyweek24/venv/lib/python3.6/site-packages/pyglet/app/base.py", line 154, in _run
    timeout = self.idle()
  File "/home/mauve/dev/pyweek24/venv/lib/python3.6/site-packages/pyglet/app/base.py", line 275, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "/home/mauve/dev/pyweek24/venv/lib/python3.6/site-packages/pyglet/clock.py", line 350, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "/home/mauve/dev/pyweek24/src/main.py", line 3259, in on_update
    player.on_update(dt)
  File "/home/mauve/dev/pyweek24/src/main.py", line 2318, in on_update
    bullet = modifier.fire(self, reticle.offset)
  File "/home/mauve/dev/pyweek24/src/main.py", line 1956, in fire
    return self.cls.fire(shooter, vector, self)
  File "/home/mauve/dev/pyweek24/src/main.py", line 1482, in fire
    b.fire(shooter, rotated_ccw, modifier)
  File "/home/mauve/dev/pyweek24/src/main.py", line 1487, in fire
    b._fire(shooter, vector, modifier)
  File "/home/mauve/dev/pyweek24/src/main.py", line 1878, in _fire
    reflected=bool(i)
TypeError: 'NoneType' object is not iterable
```

**Comment by larryhastings** [comment]
Fixed in ab777f68a22342a846c7e088d5db0f3cbec18a8e.
